spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/java17
    username: root
    password: 111
    type: com.mchange.v2.c3p0.DriverManagerDataSource
server:
  port: 177
